eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: com.frozen.bio.client
spring:
  application:
    name: com.frozen.bio.client
server:
  port: 8081