server:
  port: 8080
  servlet:
    session:
      persistent: true
      timeout: 50
      cookie:
        max-age: 7d
spring:
  session:
    store-type: redis
    redis:
      namespace: evidence
  redis:
    host: 192.168.226.130
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

