server:
  port: 8081
app:
  tmpDir: ../logs/

xxl.job.admin.addresses: http://localhost:8080
xxl.job.executor.appname: xxl-job-client
xxl.job.executor.port: 9997
xxl.job.accessToken: 
xxl.job.executor.ip: 127.0.0.1
xxl.job.executor.logpath: /data/applogs/xxl-job/jobhandler
xxl.job.executor.logretentiondays: -1